config/routes.rb
Rails.application.routes.draw do

  root 'applicants#index'

  get '/community-director-home' => 'communication#main'

  post '/community-director' => 'applicants#create' 

  get '/skype-interview' => 'applicants#skype_interview'

end

app/models/applicant.rb
class Applicant < ActiveRecord::Base
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController

	def create
		@applicant = Applicant.new(applicant_params)


		if @applicant.save
		    flash[:notice] = 'Thank you. Your application has been sent.'
		    redirect_to skype_interview_path
		end	

	end


	private

	def applicant_params
		params.require(:applicant).permit(:name, :school, :email, :phone_number, :Q1, :Q2, :Q3, :Q4, :Q5)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/communication_controller.rb
class CommunicationController < ApplicationController
end

app/helpers/applicant_helper.rb
module ApplicantHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/communication_helper.rb
module CommunicationHelper
end

app/views/applicants/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Klink | Community Director</title>
</head>
<body>
	
	<%= render 'layouts/header' %>

	<div class="post">
		<div class="apply_now">
			<h1 class="topic">Apply now!</h1>
			<h2 class="greeting">Klink Community Director</h2>
			<p class="text_body"><span style="color: #FFA800; font-size: 18px;">Finally!</span> The Klink team is hiring! Apply to be a Klink Community Director. It's a part time job. Part work. Part play.</p>
		</div>


			<%= form_for Applicant.new, url: community_director_path, method: 'post' do |f|%>
		<div class="container row">
			<div class="general_info col-md-10">
				<h4>General Information</h4>

				  <div class="form-group">
				  	<p>Name</p>
				  	<%= f.text_field :name %>
				  </div>

				  <div class="form-group">
				  	<p>School</p>
				  	<%= f.text_field :school  %>
				  </div>

				  <div class="form-group">
				  	<p>Email</p>
				  	<%= f.email_field :email %>
				  </div>

				  <div class="form-group">
				  	<p>Phone Number</p>
				  	<%= f.text_field :phone_number %>
				  </div>
			</div>
		</div>

		<div class="container row">
			<div class="app_questions col-md-10">
				<h4>Application Questions</h4>

				  <div class="form-group">
				  	<p>1) What are obstacles or threats to Klink's success in your community? How will you overcome these?</p>
				  	<%= f.text_area :Q1, :size => '65%' %>
				  </div>

				  <div class="form-group">
				  	<p>2) What proactive measures can you take to build and maintain positive relationships with the University? This could include student government, IFC, student groups, campus police, health and wellness, etc.</p>
				  	<%= f.text_area :Q2, :size => '65%' %>
				  </div>

				  <div class="form-group">
				  	<p>3) Hypothetical: Your budget for launch week and the week after is $2,000. You have two weeks to plan. How will you achieve high sales and brand recognition?</p>
				  	<%= f.text_area :Q3, :size => '65%' %>
				  </div>

				  <div class="form-group">
				  	<p>4) Hypothetical: Your budget for the month of March is $150. You are receiving 10 average-sized orders per weekend night. What do you do to increase sales?</p>
				  	<%= f.text_area :Q4, :size => '65%' %>
				  </div>

				  <div class="form-group">
				  	<p>5) A local news outlet runs a story describing Klink as a service that promotes binge drinking. The story also argues that Klink makes it easier for underaged drinkers to illegally get alcohol. How might you respond to such a story?</p>
				  	<%= f.text_area :Q5, :size => '65%' %>
				  </div>

				  <div class="form-group">
				  	<p>6) My greek organization regularly goes to the liquor store to stock up for our parties. Convince us to routinely use Klink instead.</p>
				  	<%= f.text_area :Q5, :size => '65%' %>
				  </div>

				  <div class="form-group">
				  	<p>7) Someone approaches you outside of one of your classes and tells you that he used DrinkDrivers the night before and wasn't happy. Delivery took too long and one of the items delivered was different from what he ordered. What do you do?</p>
				  	<%= f.text_area :Q5, :size => '65%' %>
				  </div>

				  <div class="form-group">
				  	<p>8) Off-campus, non-greek households possess great sales potential. What are some ways you could penetrate this market?</p>
				  	<%= f.text_area :Q5, :size => '65%' %>
				  </div>

				  <div class="form-group">
				  	<p>9) Anything else you'd like to add?</p>
				  	<%= f.text_area :Q5, :size => '65%' %>
				  </div>

			</div>
		</div>
		<div class="container row" style="margin-top: 10px;">
			<div>
				<button type="submit" class="btn btn-default">Submit</button>
			</div>

				<% end %>
		</div>
	</div>
	

</body>
</html>

app/views/applicants/skype_interview.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Klink | Community Director</title>
</head>
<body>

	<%= render "layouts/header" %>

	<div class="post">
		<h1 class="topic">Skype Interview</h1>

		<h2 class="greeting">Congratulations! </h2>

		<p class="text_body">	
			Well...we're impressed. Loved your application, and we would like to invite you to our second round of our application process: the Skype interview.
		</p>

		<h3 class="section">What to expect</h3>
			<p class="text_body">Luckily, you've already gotten past the hard part. Our skype interview is very casual, and is just a way for us to get to know you and also for you to learn a bit more about Klink and what your role would be if you're chosen as the Community Director. </p>

		<h3 class="section">Where to sign up</h3>
			<p class="text_body">In the sidebar you'll see our team's availability to chat. Please select the time that works best for you, and if none of those options work, shoot us a message. Also, put down your Skype username and feel free to add us so we're good to go when your interview time comes around.</p>

		<h3 class="section">What now?</h3>
			<p class="text_body">After you kill your Skype interview, you're done! Just sit tight and give our team a bit of time to review your application and come to a decision. We'll notify you either by email or phone regardless of our decision. Thanks for taking the time to apply to Klink, cheers!</p>
	</div>

	<div class="sidebar">
		<h1>Interview Times</h1>

			<div class="communication_tools">
				<h2>Availability</h2>
				<ul>
					<h4>Monday, July 7</h4>
					<li><a href="">2:30-3PM</a></li>
					<li><a href="">4-4:30PM</a></li>

					<h4>Tuesday, July 8</h4>
					<li><a href="">6-6:30PM</a></li>

					<h4>Wednesday, July 9</h4>
					<li><a href="">5:30-6PM</a></li>
					<li><a href="">7-7:30PM</a></li>
					</br>
					<li style="list-style-type: none; margin-left: -30px; font-size: 18px;"><a href="">None of the above work?</a></li>

				</ul>
			</div>


			<div class="contact">
				<h2>Our info</h2>
				<div class="my_info">
					<ul>
						<li style="text-transform: uppercase; padding-bottom: 8px;">Brandon Taleisnik</li>
						<li>Username: btaleis</li>
					</ul>
				</div>
				<div class="skype_button">
					<%= button_to "Next", community_director_home_path, method: "get" %>
				</div>
			</div>
	</div>

	
</body>
</html>

app/views/communication/main.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link href="application.css" rel="stylesheet" type="text/css">
	<title>Klink | Community Director</title>


</head>
<body>

	<%= render "layouts/header" %>
	<%= render "modals" %>


<div>
	<div class="post" id="accordion">
		<h1 class="topic">Guide</h1>

		<h2 class="greeting">Hello! Welcome aboard! </h2>

		<p class="text_body">	
			My name is Brandon Taleisnik, the Klink Expansion Director.
		</p>

		<p class="text_body">
			In this guide, I will outline what will be expected of you as a community director, as well as some helpful advice. Be sure to read through the entire guide; many of my insights are based on mistakes I have made as the University of Michigan Community Director, so hopefully you learn from this and it helps you avoid running into some of the problems I encountered.
		</p>

		<p class="text_body">	
			I encourage you to use this as a reference as you progress through your epic adventure as a Klink community director.
		</p>


		<h3 class="section">
		  <a data-toggle="collapse" data-parent="#accordion" href="#expectations">
          	Expectations
          </a>
		</h3>
		  <ul type="disc" id="expectations" class="collapse out">
			<li>Very cliché, but the customer always comes first, no matter what.</li>
			<li>It doesn’t matter whether the customer is right, or the customer is wrong. What does matter is that regardless of the situation, the customer is always still our customer.</li> 
			<li>If an opportunity for Klink to be brought up in casual conversation, tell people about it—word of mouth is huge.</li>
			<li>Always have swag on you to give away if you see someone on the website or talking about it.</li>
			<li>If there is a drink that a customer wants but that we don’t have listed, call the store to see if they carry the product, then get the prices and get it put on our website/app.</li>
			<li>Reward loyal customers whenever you can.</li>
			<li>Never make a promise you can’t 100% keep.</li>
			<li>When something goes wrong with an order, make sure that once everything is sorted out, the customer ends up happy. Give them free drinks, refund them, etc. so that we never have a customer that has a bad experience through us. Rumors spread like wildfire and the more we can limit the bad publicity, the better.</li>
			<li>Make sure retailers are aware of big orders that have been secured in advance for the upcoming weekend so they can prepare with employees, quantities, etc.</li>
			<li>Don’t offer big deals to groups unless it’s absolutely critical, or if they won’t use us if you don’t. Consult Jeff, Craig, or myself if you aren’t sure what to do in a situation. If they ask for deals for ordering bulk quantities, the main “deal” we want to give away most the time is just free swag because that benefits us too by giving us advertising opportunities, whereas giving free chaser and cups, practically only the person in charge of placing the order will know that we hooked em up.</li>
		  </ul>

		<h3 class="section">
			<a data-toggle="collapse" data-parent="#accordion" href="#customer_service">
          	Customer Service Tips
          	</a>
		</h3>  
		  <ul type="disc" class="collapse out" id="customer_service">
		  	<li>TOR (Time of Response) is what differentiates good and great customer service; statistics show that when a customer’s complaint is addressed immediately, they will be more forgiving and it will be easier to regain their trust/loyalty. If you wait a few days to right a wrong, it may be too late, and the customer may forever have a bad taste and impression of our company.</li>
			<li>Your job essentially boils down to the acquisition and maintenance of customers.</li>
			<ul type="circle">
				<li>If someone has a mediocre/poor experience, you must do everything in your power to make sure that that customer leaves wanting to come back. Losing $20 on that customer is	 a long-term investment that will ultimately yield higher returns than if you are solely profit-oriented and are reluctant to spend the extra money to maintain a customer.</li>
			</ul>
			<li>Please review the "Customer Apology Approach" and the "Klink Communications Standards"</li>
		  </ul>

		<h3 class="section">
			<a data-toggle="collapse" data-parent="#accordion" href="#before_launch">
          	Before Launch
          	</a>
        </h3>
		  <ul type="disc" id="before_launch" class="collapse out">
			<li>Take inventory at partnered liquor store</li>
			<li>Do research and find all/any organizations we could do promos/sponsorships with.</li>
			<ul type="circle">
				<li>For example, at Michigan, we are working with a company called Bar2Bar 	transportation and a promo could be that we pay for everyone’s cost of using Bar2Bar, as long as they have our app downloaded upon entry.</li>
			</ul>
			<li>Odds are, the email you’re going to send to Greek life once we launch is going to have so many spam trigger words that it’ll probably be filtered into the junk mail folder. Start drafting what you plan on saying in the email ahead of time, and test to make sure it goes through fine by sending it to our emails, so that we don’t run into the spam issue. Word selection is going to be critical; use my email I sent to Greek life as a model. Please use the "Fraternity President Email" in Additional Resource as an example.</li>
			<ul type="circle">
				<li>If you have access to a certain group email list that would be a good target audience, try to send these emails to them.</li>
			</ul>
			<li>Create an excel spreadsheet like the "Greek Life Contact Spreadsheet" with info about each Greek organization. This is a great organizational resource that I encourage you to utilize.</li>
			<li>Before you start trying to secure big orders, you need to make sure our partners are prepared to accommodate large quantities of bottom shelf alcohol. They need to have hundreds of handles of vodka, beer, cups in bulk, etc.</li>
		  </ul>

		<h3 class="section">
			<a data-toggle="collapse" data-parent="#accordion" href="#during_launch">
          	During Launch
          	</a>
		</h3>
		  <ul type="disc" id="during_launch" class="collapse out">
		  	<li>When we launch, we will most likely start with a Facebook post. Advertise the shit out of it. Post on all big school-related group fb pages, your own fb, ask your friends to share it, etc.</li>
		  	<ul type="circle">
				<li>On our first post once we launched, I got almost 2000 organic views in 	less than an hour, 7000+ total organic views, 150+ likes, and 70+ shares; 	by the time you launch, we’ll have more likes on our fb page than when I 	started, so it’s expected that you will be able to top my numbers.</li>
			</ul>
			<li>Send an email to all Greek life presidents the day you launch, and have it revised by myself or founders.</li>
			<li>Cross-reference the email order confirmations and do facebook stalking to find out if they’re involved in a greek organization.</li>
			<ul type="circle">
				<li>If they are, put a check mark next to that organization.</li>
			</ul>
			<li>Once you launch, go on major school pages (i.e. Class of 2017 fb page, University twitter account, greek life accounts, etc.) and follow everyone on twitter, Instagram, and share our info on fb.</li>
			<li>After the initial fb/social media push, stand in the busiest part of campus and pass out fliers; you have to walk the line between not being intrusive, and getting your advertisement across.</li>
			<ul type="circle">
				<li>You’ll realize that when you’re advertising a product/service that people want, you’d be amazed with the overwhelmingly excited/positive response you’d get. I would just wait for people to walk by and hand a flier and say “Alcohol delivery service, you can’t turn this down! Check it out!” or something of the sort. Don’t be overly serious, but be professional. Feel free to joke around with people because it builds a bond—if people like you, they’ll want to help us and try our service.</li>
			</ul>
		  </ul>

		<h3 class="section">
			<a data-toggle="collapse" data-parent="#accordion" href="#after_launch">
          	After Launch
          	</a>
        </h3>
		  <ul type="disc" id="after_launch" class="collapse out">
			<li>After you send out the email to Greek life presidents, reach out to any friends you know in each organization and ask them if their president forwarded the email to their chapter/social chair, and if not, ask that friend to ask their president to do so.</li>
			<li>After a few weeks, contact all organizations who do not have a check mark, and find out what it is that’s holding them back from making an order through us, and work with the team to devise a plan to cater their needs (10% off, sponsor a party, free Redbulls, free swag, etc.)</li>
			<li>Follow-up on frats who expressed interest but still haven’t ended up placing an order. Often, all they need is a reminder.</li>
			<li>Start brainstorming ways to capture the non-Greek market.</li>
		  </ul>

		<h3 class="section">
			<a data-toggle="collapse" data-parent="#accordion" href="#marketing_ideas">
          	Marketing Ideas
          	</a>
        </h3>
		  <ul type="disc" id="marketing_ideas" class="collapse out">
		  	<li>Try to get a banner hung in major student bars.</li>
			<li>I put Klink stickers on my phone case and computer, and that drew a lot of attention and sparked conversation because people ask me what the stickers are for.</li>
			<li>Make posts that show school spirit (i.e. “It’s almost tip off! #GoBlue #AlcoholDelivery”)</li>
			<li>A frequent promo we do to secure a lot of big orders is that we give them a free 2L of chaser for every handle they buy, as well as 250 free cups for every 10 handles on their first order.</li>
			<li>Once a frat orders for a party, if they are happy with their experience, try to get them to help us spread the word to other fraternities and give them a few shirts/stickers/bottle openers in return for their help and using our service.</li>
			<li>During finals/midterm time, leave pens all over the library and lecture halls; whenever I study, I always leave the pen I was using behind on the table and hope it ends up in the hands of a future customer.</li>
			<li>Send direct mail filers to the community.</li>
		  </ul>
		<h3 class="section">
			<a data-toggle="collapse" data-parent="#accordion" href="#advice">
          	Advice
          	</a>
        </h3>
		  <ul type="disc" id="advice" class="collapse out">
			<li>Media publicity is huge. The amount of attention/stir from getting one news article published was unbelievable. We got tons of tweets directed towards us, new followers, tons of orders, etc. If you have any connections to a school newspaper, radio show, etc., reach out to them. The media always wants to discover the new innovative things going on in the area, so they’ll probably be very receptive of your outreach and be eager to run a story on Klink.</li>
			<li>It’s always better to talk to social chairs directly instead of presidents. Greek life presidents get dozens of emails about promotional stuff so they may just trash the email right away; it’s the social chair whose life is being made easier by not having to coordinate making alcohol runs so we want them to be in the loop.</li>
			<li>Anticipate days that may have heavy traffic (big sporting events, concerts, etc.) and discuss with us how to handle it. On gamedays, for example, there will be thousands of people near campus and will make it very difficult or even impossible for our drivers to navigate and deliver anything in a timely manner.</li>
			<li>Realize that it’s not that people don’t want to use our service, they just sometimes forget it exists. For example, someone said “yea I’m gonna go pick up some beers or something from the store” I shouted out “Klink it!” and he says “oh yea! Good call!” so we’ve gotta have a constant presence in people’s lives through our advertising.</li>
		  </ul>
	</div>

	<div class="resources_sidebar">
		<h1>Additional Resources</h1>
			<div class="communication_tools">
				<h2>Communication Tools</h2>
				<ul>
					<li><a href="#frat_email" data-toggle="modal" class="btn" data-target="#frat_email">Fraternity President Email</a></li>
					<li><a href="#frat_fb" data-toggle="modal" class="btn" data-target="#frat_fb">Fraternity President Facebook Follow-up</a></li>
					<li><a href="#party_sponsorship" data-toggle="modal" class="btn" data-target="#party_sponsorship">Party Sponsorship Request</a></li>
					<li><a href="#customer_apology" data-toggle="modal" class="btn" data-target="#customer_apology">Customer Apology Approach</a></li>
					<li><a href="#communication_standards" data-toggle="modal" class="btn" data-target="#communication_standards">Klink Communications Standards</a></li>
					<li><a href="#media_help" data-toggle="modal" class="btn" data-target="#media_help">Talking Points for the Media</a></li>
					<li><a href="#greek_contacts" data-toggle="modal" class="btn" data-target="#greek_contacts">Greek Life Contact Spreadsheet</a></li>


				</ul>
			</div>


			<div class="contact">
				<h2>Questions?</h2>
				<div class="my_info">
					<ul>
						<li style="text-transform: uppercase; padding-bottom: 8px;">Brandon Taleisnik</li>
						<li>714-788-9009</li>
						<li>btaleisnik@gmail.com</li>
					</ul>
				</div>
			</div>
	</div>
</div>

	

</body>
</html>

app/views/layouts/_header.html.erb
	<div class="header">
		<span><a href="community-director-home"class="logo"><img alt="Klink" title="Klink - Alcohol Delivery" src="assets/klink_logo.png"></a></span>

		<span class="subtitle">alcohol delivery.</span>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Klink</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:notice] -%>
  <div class = "alert alert-success"><%= flash[:notice] %></div>
<% end %>
<% if flash[:error] -%>
  <p class='error'><%=h flash[:error] %></p>
<% end -%>

<%= yield %>


</body>
</html>